[auto-bump][chart] nvidia-0.3.6
mesosphere/kubernetes-base-addons pull request #1133
Opened 2021-05-18 10:45 UTC by d2iq-dispatch

**What type of PR is this?**
Chore

**What this PR does/ why we need it**:
Update Nvidia Prometheus exporter and Grafana dashboard.

**Which issue(s) this PR fixes**:
https://jira.d2iq.com/browse/D2IQ-75525
https://jira.d2iq.com/browse/D2IQ-75529
https://jira.d2iq.com/browse/D2IQ-75528
https://jira.d2iq.com/browse/D2IQ-75526

**Special notes for your reviewer**:
This was tested using the procedure described in the `TESTING.md` file. To test, create a Konvoy cluster with GPU nodes according to https://docs.d2iq.com/dkp/konvoy/1.8/gpu/ and with the Konvoy `cluster.yaml` pointing to
```yaml
  - configRepository: https://github.com/mesosphere/kubernetes-base-addons
    configVersion: D2IQ-75525/bump-dcgm
```

See https://jira.d2iq.com/browse/D2IQ-75528 for some screenshots of the Grafana dashboard.

**Does this PR introduce a user-facing change?**:

```release-note
Updated Nvidua Prometheus outputs and Grafana dashboard.
```

**Checklist**

* [x] *If a chart is changed, the chart version is correctly incremented.*
* [x] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

2021-05-19 20:46 UTC, joejulian requested changes

2021-05-19 20:46 UTC, joejulian commented on addons/nvidia/nvidia.yaml
> +    catalog.kubeaddons.mesosphere.io/addon-revision: "0.2.0-9"
Increment the addon patch version to account for the patch version change of the chart. Only increment release version when the only change is to the addon resource alone.

```suggestion
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.2.1-0"
```

2021-05-25 09:05 UTC, jongiddy commented
@joejulian I've accepted your change. Is this OK now?

2021-05-27 22:14 UTC, joejulian approved these changes

2021-05-28 09:14 UTC, mhrabovcin approved these changes

2021-05-28 09:14 UTC, merged

2021-05-28 09:29 UTC, jongiddy commented
@mesosphere-mergebot backport release/3 release/4