[release/3][BACKPORT] [tests] [flagger] [kiali] Update references to prometheus resources
mesosphere/kubernetes-base-addons pull request #1151
Opened 2021-05-20 20:43 UTC by mesosphere-mergebot

This is a backport of the following PR:

https://github.com/mesosphere/kubernetes-base-addons/pull/1135

**What type of PR is this?**

Bug

**What this PR does/ why we need it**:

This updates some lingering references to Prometheus resources that were changed with https://github.com/mesosphere/kubernetes-base-addons/pull/1129. 

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-75500

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Checklist**

* [x] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [x] The core changes are covered by tests.
* [x] The documentation is updated where needed.
Before merging, conflicts in the following files need to be resolved: 
test/dispatch_test_install_upgrade.sh
Makefile
addons/kiali/kiali.yaml

2021-05-20 21:36 UTC, joejulian requested changes
Release 3 doesn't ship with konvoy 8. This probably should be upgraded to the latest 1.7 though.

2021-05-20 22:16 UTC, joejulian approved these changes

2021-05-24 11:11 UTC, alejandroEsc approved these changes
lgtm

2021-05-25 21:30 UTC, branden commented
Tests are failing due to the old version of flagger failing to come up healthy:

```
      harness.go:73: ERROR: addon flagger using the previous version '0.19.0-4' did not come up healthy
```

This error indicates a problem with flagger and/or related tests on the release/3 branch. This PR fixes a regression that causes flagger and kiali metrics to go missing from Prometheus. Given that, I'll merge despite the CI failures.

2021-05-25 21:31 UTC, merged