bump kubeaddons-addon-initializer to v0.5.4 to match the rest of the addons
mesosphere/kubernetes-base-addons pull request #1423
Opened 2022-02-03 00:30 UTC by joejulian

**What type of PR is this?**

Bug

**What this PR does/ why we need it**:

Use one single common version of kubeaddons-addon-initializer throughout all of KBA

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

**Checklist**

* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

2022-02-03 00:30 UTC, joejulian commented
@mesosphere-mergebot backport  release/4

2022-02-03 23:06 UTC, gracedo approved these changes

2022-02-03 23:07 UTC, gracedo requested changes
oh wait we should bump the revision number

2022-02-04 00:56 UTC, gracedo approved these changes

2022-02-04 01:05 UTC, gracedo commented
we actually also need to bump opsportal to the latest version which pulls in the same version of kommander ui as kommander, closing this in favor of https://github.com/mesosphere/kubernetes-base-addons/pull/1380. I've cherry-picked the initializer img to that branch

2022-02-04 01:05 UTC, closed without merging