Ae/split/dummy
mesosphere/kubernetes-base-addons pull request #817
Opened 2021-01-26 17:41 UTC by alejandroEsc

TEST for https://github.com/mesosphere/kubernetes-base-addons/pull/809

**What type of PR is this?**

**What this PR does/ why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

2021-01-26 18:43 UTC, gracedo commented
I think I found the issue causing these tests to fail, commented here https://github.com/mesosphere/kubernetes-base-addons/pull/809/files#r564745622

2021-01-28 00:07 UTC, alejandroEsc commented on test/groups.yaml
> -    - "cert-manager"
think you meant to only copy these right?

2021-01-28 00:10 UTC, alejandroEsc commented on test/addons_test.go
> -	prometheusGroupName = "prometheus"
Why remove the prometheus group name?

2021-01-29 19:57 UTC, alejandroEsc commented
was able to fix the issues why this was failing, running another test with a few more changes and will rebase to squash commits

2021-01-29 20:50 UTC, alejandroEsc commented
ok passed again. So looking really good. Next going to remove comments for install only.

2021-01-29 22:04 UTC, alejandroEsc commented
Installation and upgrade both passed. Working on removing testing charts (from Elastic search and Kibana PR). Now removing these charts, leaving all the changes we want to push on master. If green then we are ready.

2021-01-29 22:27 UTC, s12chung commented on test/dispatch-ci.sh
> +source ./scripts/setup-konvoy.sh v1.6.1
thanks

2021-01-29 22:27 UTC, s12chung approved these changes

2021-01-29 22:31 UTC, gracedo approved these changes
🥳

2021-01-29 22:31 UTC, gracedo commented on test/addons_test.go
> +func testgroup(t *testing.T, groupName string, version string, jobs ...clusterTestJob) error {
🙌

2021-01-29 23:48 UTC, joejulian requested changes

2021-01-30 00:16 UTC, alejandroEsc commented on test/addons_test.go
> +		path, _ = os.Getwd()
i just want this to pass for now. This is holding back the work on ES and i rather not spend a few more hours debugging additional issues atm.

2021-01-30 00:33 UTC, joejulian approved these changes

2021-01-30 01:38 UTC, merged

2021-02-22 22:14 UTC, joejulian commented
@mesosphere-mergebot backport release/3.3